# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pnode

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install required python packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest cython scipy torch
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      uses: py-actions/flake8@v2
      with:
        ignore: "F401,F403,E203,E402,E501,W503"
        exclude: "examples-sinode/grand,examples-sinode/KS/KS_node.py"
        max-line-length: "100"
    - name: Install petsc
      env:
        scalar: real
      run: |
        bash ${GITHUB_WORKSPACE}/.github/workflows/build.sh
    - name: Test with pytest
      run: |
        export PYTHONPATH=${{ env.PETSC_DIR }}/${{ env.PETSC_ARCH }}/lib:$PYTHONPATH
        pytest tests
